### ISSUE TITLE
MemCachedClient 没提交

### ISSUE THREAD

**Issue by limingios** [thomasj-git/springcache-ext#1]
![image](https://user-images.githubusercontent.com/13448645/72491282-8780e080-3854-11ea-8482-9ce15bde4fd3.png)

**Comment by thomasj-git** [comment]
https://github.com/downloads/gwhalin/Memcached-Java-Client/java_memcached-release_2.6.1.zip
or 
https://pan.baidu.com/s/1VgYl3_SpCpIf-HJ7-mMhaQ 
提取码: 2upn

**Comment by limingios** [comment]
<dependency>
            <groupId>com.danga</groupId>
            <artifactId>java_memcached</artifactId>
            <version>2.6.6</version>
        </dependency>

才开始熟悉spring cache-ext  能否提供个 springboot的实例 上去

**Comment by thomasj-git** [comment]
https://github.com/downloads/gwhalin/Memcached-Java-Client/java_memcached-release_2.6.1.zip
or
https://pan.baidu.com/s/1VgYl3_SpCpIf-HJ7-mMhaQ
提取码: 2upn

**Comment by thomasj-git** [comment]
> com.danga java_memcached 2.6.6
> 才开始熟悉spring cache-ext 能否提供个 springboot的实例 上去

已添加example，参考REAME自述文档
